name: Deploy to DirectAdmin Final

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: mireymireina.jerryyss.my.id
        # Gunakan login lengkap sesuai screenshot
        username: mireymireina@jerryyss.my.id
        password: ${{ secrets.FTP_PASSWORD }}
        # Karena akun FTP ini sudah dikunci ke folder public_html, 
        # kita gunakan './' agar file langsung masuk ke situ
        server-dir: ./
        protocol: ftp
